version: '3'

services:

  postgres:
    container_name: postgres_db_task
    image: postgres:latest
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_db