spring:
  application:
    name: Task-tracer

  jpa:
    generate-ddl: true
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5437/task_db
    username: postgres
    password: postgres

server:
  port: 8088

springdoc:
  api-docs:
    path: /api-docs

app:
  jwt:
    secret: "53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
    expirationTimeAccessToken: 3600000
    expirationTimeRefreshToken: 86400000
